use cashonlinedb;

insert into usuario (email,first_name,last_name) values ('nando@gmail.com', 'fernando', 'lopez');
insert into usuario (email,first_name,last_name) values ('damian@gmail.com', 'damian', 'marasco');
insert into usuario (email,first_name,last_name) values ('ana@gmail.com', 'ana', 'ciarlante');
insert into usuario (email,first_name,last_name) values ('bruno@gmail.com', 'bruno', 'maradona');
insert into usuario (email,first_name,last_name) values ('selene@gmail.com', 'selene', 'sosa');
insert into usuario (email,first_name,last_name) values ('matias@gmail.com', 'matias', 'leoz');
insert into usuario (email,first_name,last_name) values ('ruben@gmail.com', 'ruben', 'rimoldi');
insert into usuario (email,first_name,last_name) values ('myriam@gmail.com', 'myriam', 'roa');
insert into usuario (email,first_name,last_name) values ('silvia@gmail.com', 'silvia', 'artesi');
insert into usuario (email,first_name,last_name) values ('mario@gmail.com', 'mario', 'ciarlante');


insert into loan (total, id_usuario) values (25000,9);
insert into loan (total, id_usuario) values (4000,9);
insert into loan (total, id_usuario) values (65000,2);
insert into loan (total, id_usuario) values (66000,9);
insert into loan (total, id_usuario) values (98700,3);
insert into loan (total, id_usuario) values (2670,3);
insert into loan (total, id_usuario) values (2500,4);
insert into loan (total, id_usuario) values (2870,6);
insert into loan (total, id_usuario) values (23400,6);
insert into loan (total, id_usuario) values (35400,6);
insert into loan (total, id_usuario) values (8900,7);
insert into loan (total, id_usuario) values (7000,7);
insert into loan (total, id_usuario) values (5000,2);
insert into loan (total, id_usuario) values (5000,2);
insert into loan (total, id_usuario) values (5000,3);
insert into loan (total, id_usuario) values (6000,7);
insert into loan (total, id_usuario) values (8000,8);
insert into loan (total, id_usuario) values (9000,9);
insert into loan (total, id_usuario) values (35000,3);
insert into loan (total, id_usuario) values (56000,3);
insert into loan (total, id_usuario) values (43000,3);
insert into loan (total, id_usuario) values (25000,10);
insert into loan (total, id_usuario) values (4000,10);
insert into loan (total, id_usuario) values (65000,10);
insert into loan (total, id_usuario) values (66000,8);
insert into loan (total, id_usuario) values (98700,9);
insert into loan (total, id_usuario) values (2670,9);
insert into loan (total, id_usuario) values (2500,6);
insert into loan (total, id_usuario) values (2870,5);
insert into loan (total, id_usuario) values (23400,7);
insert into loan (total, id_usuario) values (35400,8);
insert into loan (total, id_usuario) values (8900,2);
insert into loan (total, id_usuario) values (7000,3);
insert into loan (total, id_usuario) values (5000,4);
insert into loan (total, id_usuario) values (5000,5);
insert into loan (total, id_usuario) values (5000,6);
insert into loan (total, id_usuario) values (6000,8);
insert into loan (total, id_usuario) values (8000,7);
insert into loan (total, id_usuario) values (9000,10);
insert into loan (total, id_usuario) values (35000,1);
insert into loan (total, id_usuario) values (56000,2);
insert into loan (total, id_usuario) values (43000,4);
insert into loan (total, id_usuario) values (25000,3);
insert into loan (total, id_usuario) values (4000,5);
insert into loan (total, id_usuario) values (65000,6);
insert into loan (total, id_usuario) values (66000,7);
insert into loan (total, id_usuario) values (98700,8);
insert into loan (total, id_usuario) values (2670,9);
insert into loan (total, id_usuario) values (2500,10);
insert into loan (total, id_usuario) values (2870,8);
insert into loan (total, id_usuario) values (23400,3);
insert into loan (total, id_usuario) values (35400,2);
insert into loan (total, id_usuario) values (8900,4);
insert into loan (total, id_usuario) values (7000,5);
insert into loan (total, id_usuario) values (5000,6);
insert into loan (total, id_usuario) values (5000,3);
insert into loan (total, id_usuario) values (5000,7);
insert into loan (total, id_usuario) values (6000,9);
insert into loan (total, id_usuario) values (8000,10);
insert into loan (total, id_usuario) values (9000,8);
insert into loan (total, id_usuario) values (35000,6);
insert into loan (total, id_usuario) values (56000,7);
insert into loan (total, id_usuario) values (43000,6);
insert into loan (total, id_usuario) values (25000,8);
insert into loan (total, id_usuario) values (4000,10);
insert into loan (total, id_usuario) values (65000,1);
insert into loan (total, id_usuario) values (66000,1);
insert into loan (total, id_usuario) values (98700,1);
insert into loan (total, id_usuario) values (2670,2);
insert into loan (total, id_usuario) values (2500,4);
insert into loan (total, id_usuario) values (2870,4);
insert into loan (total, id_usuario) values (23400,4);
insert into loan (total, id_usuario) values (35400,5);
insert into loan (total, id_usuario) values (8900,5);
insert into loan (total, id_usuario) values (7000,5);
insert into loan (total, id_usuario) values (5000,6);
insert into loan (total, id_usuario) values (5000,6);
insert into loan (total, id_usuario) values (5000,6);
insert into loan (total, id_usuario) values (6000,10);
insert into loan (total, id_usuario) values (8000,10);
insert into loan (total, id_usuario) values (9000,8);
insert into loan (total, id_usuario) values (35000,7);
insert into loan (total, id_usuario) values (56000,8);
insert into loan (total, id_usuario) values (43000,2);
